### ISSUE TITLE
interface{}

### ISSUE THREAD

**Issue by termith** [termith/minimblog#11]
https://github.com/termith/minimblog/blob/f9524e8ff6c8346af44568fdf3df19fee71e0a87/common/logging/logging.go#L17

[Here](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=7m36s) Rob Pike says that this is bad practice

**Comment by Aelnor** [comment]
It was not about the case. Take a look on println prototype, it has the same arguments. It makes no sense to forward args in another way.
